apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ipv4-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ipv6-pool
  namespace: metallb-system
spec:
  addresses:
    - 2001:db8:1::200-2001:db8:1::250