apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels: { name: nvidia-device-plugin }
  template:
    metadata: { labels: { name: nvidia-device-plugin } }
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
      - name: nvidia-device-plugin
        image: nvcr.io/nvidia/k8s-device-plugin:v0.14.4
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
