apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: infra
type: Opaque
data:
  credentials.json: <BASE64-ARGO-TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: infra
spec:
  replicas: 2
  selector: { matchLabels: { app: cloudflared } }
  template:
    metadata: { labels: { app: cloudflared } }
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2024.4.0
        args: ["tunnel","run","--no-autoupdate","--origincert=/etc/cloudflared/credentials.json","--url=http://traefik.kube-system.svc.cluster.local:80"]
        volumeMounts:
        - name: creds
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: cloudflared-token
