apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.32.3
networking:
  podSubnet: 10.42.0.0/16
proxy:
  config:
    mode: nftables
    featureGates:
      NFtablesProxyMode: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: nftables
featureGates:
  NFtablesProxyMode: true
